import datetime

assertions = [

{'district': '46',
 'email': 'AMaisel@council.nyc.gov',
 'firstname': 'Alan N.',
 'fullname': 'Alan N. Maisel',
 'identifiers': [{'identifier': '125488', 'scheme': 'legistar_id'},
                 {'identifier': '57421577-C58B-487E-BBD1-BC7522FEE828',
                  'scheme': 'legistar_guid'}],
 'image': 'http://legistar.council.nyc.gov/View.ashx?M=P&ID=125488&GUID=57421577-C58B-487E-BBD1-BC7522FEE828',
 'lastname': 'Maisel',
 'memberships': [{'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'City Council',
                  'role': 'Council Member',
                  'start_date': datetime.datetime(2014, 1, 1, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on Community Development',
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on Education',
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on Parks and Recreation',
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on Standards and Ethics',
                  'role': 'CHAIRPERSON',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on State and Federal Legislation',
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on Veterans',
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)}],
 'notes': 'District 46 - Council Member - Democrat ~ Chair - Committee on '
          'Standards & Ethics',
 'party': 'Democrat',
 'sources': [{'note': 'people search, people search table',
              'url': 'http://legistar.council.nyc.gov/People.aspx'},
             {'note': 'person detail, person detail table',
              'url': 'http://legistar.council.nyc.gov/PersonDetail.aspx?ID=125488&GUID=57421577-C58B-487E-BBD1-BC7522FEE828&Search='}],
 'website': 'http://council.nyc.gov/d46/html/members/home.shtml'},

 {'district': '5',
 'email': 'BKallos@council.nyc.gov',
 'firstname': 'Ben',
 'fullname': 'Ben Kallos',
 'identifiers': [{'identifier': '125480', 'scheme': 'legistar_id'},
                 {'identifier': 'D0100CC7-C61B-444B-BCD8-572807E91278',
                  'scheme': 'legistar_guid'}],
 'image': 'http://legistar.council.nyc.gov/View.ashx?M=P&ID=125480&GUID=D0100CC7-C61B-444B-BCD8-572807E91278',
 'lastname': 'Kallos',
 'memberships': [{'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'City Council',
                  'role': 'Council Member',
                  'start_date': datetime.datetime(2014, 1, 1, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on Governmental Operations',
                  'role': 'CHAIRPERSON',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on Land Use',
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Committee on State and Federal Legislation',
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': "Committee on Women's Issues",
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)},
                 {'end_date': datetime.datetime(2017, 12, 31, 0, 0),
                  'org': 'Subcommittee on Landmarks, Public Siting and '
                         'Maritime Uses',
                  'role': 'Committee Member',
                  'start_date': datetime.datetime(2014, 1, 22, 0, 0)}],
 'notes': 'District 5 - Council Member - Democrat ~ Chair - Committee on '
          'Governmental Operations',
 'party': 'Democrat',
 'sources': [{'note': 'people search, people search table',
              'url': 'http://legistar.council.nyc.gov/People.aspx'},
             {'note': 'person detail, person detail table',
              'url': 'http://legistar.council.nyc.gov/PersonDetail.aspx?ID=125480&GUID=D0100CC7-C61B-444B-BCD8-572807E91278&Search='}],
 'website': 'http://council.nyc.gov/d5/html/members/home.shtml'}

]
